version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: banker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.docker-images:/var/lib/postgresql/data