server:
  port: 8080

spring:
  application:
    name: banker
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 1
        format_sql: ${SHOW_SQL:true}
    show-sql: ${SHOW_SQL:true}

  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:${DB_PORT:5432}/${POSTGRES_DB:banker}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      connection-timeout: 2000
      leak-detection-threshold: 6000
      maximum-pool-size: 50
      minimum-idle: 10
      pool-name: BankersPgPool
      schema: public
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
