# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
    - name: run tests
      run: mvn clean install

      container-job:
        runs-on: ubuntu-latest
        container: node:10.18-jessie

        services:
          postgres:
            image: postgres
            env:
              POSTGRES_PASSWORD: postgres
              POSTGRES_HOST: postgres
              POSTGRES_PORT: 5432
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5



